# Fly.io Configuration for Chat with Knowledge Base
# Documentation: https://fly.io/docs/reference/configuration/

app = "chat-kb-app"    # Change this to your desired app name
primary_region = "sjc" # Change to your preferred region

[build]
dockerfile = "Dockerfile"

[env]
# Non-sensitive environment variables
# Sensitive variables should be set using: fly secrets set KEY=value

# Database Configuration (non-sensitive parts)
MYSQL_DATABASE = "chat_kb"
MYSQL_USER = "chatuser"

# Service URLs (will be updated for production)
BIFROST_API_URL = "http://localhost:8080" # Update for your Bifrost deployment
QDRANT_URL = "http://localhost:6333"      # Update for your Qdrant deployment

# File Upload Configuration
UPLOAD_DIR = "/app/uploads"
MAX_FILE_SIZE = "10485760"

# Application Configuration
NODE_ENV = "production"
PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "uploads_volume"
destination = "/app/uploads"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

# Optional: Deploy multiple regions for better performance
# [[regions]]
#   name = "sjc"
#   primary = true
#
# [[regions]]
#   name = "iad"
